name: Keep Alive

on:
  repository_dispatch:
    types: [manual_trigger]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: keep-alive

      - name: Keep Alive Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          TIME=$(date -Isecond -u)
          echo $TIME >> keep-alive.txt
          git add keep-alive.txt
          git commit -m "keep-alive: $TIME"
          git push origin keep-alive